import { ChainId } from '@uniswap/sdk';
import { Configuration } from './lift/config';
import { BankInfo } from './lift';

const configurations: { [env: string]: Configuration } = {
  development: {
    chainId: ChainId.MAINNET,
    etherscanUrl: 'https://etherscan.io',
    defaultProvider: 'https://mainnet.infura.io/v3/a3080603f6a64a42825966e701f8917c',
    deployments: require('./lift/deployments/deployments.mainnet.json'),
    externalTokens: {
      'wBTC': ['0x2260fac5e5542a773aa44fbcfedf7c193bc2c599', 8],
      'wETH': ['0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 18],
      'wETH-lfETH': ['0xc92a6738d66ebffbacff9310255b949eb960c21a', 18], 
      'wBTC-lfBTC': ['0xd975b774c50aa0aeacb7b546b86218c1d7362123', 18],
      'lfBTC-LIFT': ['0x0e250c3ff736491712c5b11ecee6d8dbfa41c78f', 18],
      'wBTC-lfBTC-Harvest': ['0x17Ea335B82844212468000e7Aeb5F55D63948c47', 18],
      'lfBTC-LIFT-Harvest': ['0x5ed17cA557359eAB39FEA1de8240BaC4b9C7BECa', 18],
      'iFARM': ['0x1571ed0bed4d987fe2b498ddbae7dfa19519f651', 18],
      'alUSD': ['0xbc6da0fe9ad5f3b0d58160288917aa56653660e9', 18],
      'KBTC': ['0xe6c3502997f97f9bde34cb165fbce191065e068f', 18],
      'PICKLE': ['0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5', 18],
      'BASv2': ['0x106538cc16f938776c7c180186975bca23875287', 18],
    },
    baseLaunchDate: new Date('2021-05-01T14:00:00Z'),
    boardroomLaunchesAt: new Date('2021-05-01T14:00:00Z'),
    refreshInterval: 30000,
    gasLimitMultiplier: 1.7,
  },
  production: {
    chainId: ChainId.MAINNET,
    etherscanUrl: 'https://etherscan.io',
    defaultProvider: 'wss://mainnet.infura.io/ws/v3/ff0b78e4bf084b87a48b1c2f732a2c18',
    deployments: require('./lift/deployments/deployments.mainnet.json'),
    externalTokens: {
      'wBTC': ['0x2260fac5e5542a773aa44fbcfedf7c193bc2c599', 8],
      'wETH': ['0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 18],
      'wETH-lfETH': ['0xc92a6738d66ebffbacff9310255b949eb960c21a', 18], 
      'wBTC-lfBTC': ['0xd975b774c50aa0aeacb7b546b86218c1d7362123', 18],
      'lfBTC-LIFT': ['0x0e250c3ff736491712c5b11ecee6d8dbfa41c78f', 18],
      'wBTC-lfBTC-Harvest': ['0x17Ea335B82844212468000e7Aeb5F55D63948c47', 18],
      'lfBTC-LIFT-Harvest': ['0x5ed17cA557359eAB39FEA1de8240BaC4b9C7BECa', 18],
      'iFARM': ['0x1571ed0bed4d987fe2b498ddbae7dfa19519f651', 18],
      'alUSD': ['0xbc6da0fe9ad5f3b0d58160288917aa56653660e9', 18],
      'KBTC': ['0xe6c3502997f97f9bde34cb165fbce191065e068f', 18],
      'PICKLE': ['0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5', 18],
      'BASv2': ['0x106538cc16f938776c7c180186975bca23875287', 18],
    },
    baseLaunchDate: new Date('2021-03-22T04:00:00Z'),
    boardroomLaunchesAt: new Date('2021-05-01T14:00:00Z'),
    refreshInterval: 30000,
    gasLimitMultiplier: 1.7,
  },
};

export const bankDefinitions: { [contractName: string]: BankInfo } = {
  wBTClfBTCPTokenSharePool: {
    name: 'wBTC-lfBTC',
    contract: 'wBTClfBTCLPTokenSharePool',
    depositTokenName: 'wBTC-lfBTC',
    instructions: 'The scoop on the wBTC-lfBTC pool.  This pool has allocated 2500 LIFT tokens per week for 104 weeks; 2 years!  To add liquidity to this pool you must have equal parts wBTC and lfBTC.  To buy lfBTC you must visit SushiSwap, and buy lfBTC from the existing wBTC/lfBTC Pool.  Once you have equal parts wBTC and lfBTC you can stake them into the wBTC/lfBTC Pool.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: false,
    poolTVL: "$0",
    sort: 1,
    apy: 0,
    perWeek: 2500,
  },
  wETHlfETHLPTokenSharePool: {
    name: 'wETH-lfETH',
    contract: 'wETHlfETHLPTokenSharePool',
    depositTokenName: 'wETH-lfETH',
    instructions: 'The scoop on the wETH-lfETH pool.  This pool has allocated 2500 LIFT tokens per week for 104 weeks; 2 years!  To add liquidity to this pool you must have equal parts wETH and lfETH.  To buy lfETH you must visit SushiSwap, and buy lfETH from the existing wETH/lfETH Pool.  Once you have equal parts wETH and lfETH you can stake them into the wETH/lfETH Pool.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: false,
    poolTVL: "$0",
    sort: 1,
    apy: 0,
    perWeek: 2500,
  },
  lfBTCLIFTLPTokenSharePool: {
    name: 'lfBTC-LIFT',
    contract: 'lfBTCLIFTLPTokenSharePool',
    depositTokenName: 'lfBTC-LIFT',
    instructions: 'The scoop on the lfBTC-LIFT pool.  This pool has allocated 7500 LIFT tokens per week for 104 weeks; 2 years!  To add liquidity to this pool you must have equal parts wBTC and lfBTC.  To buy lfBTC you must visit SushiSwap, and buy lfBTC from the existing wBTC/lfBTC Pool.  Once you have equal parts wBTC and lfBTC you can stake them into the lfBTC/LIFT Pool.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: false,
    poolTVL: "$0",
    sort: 2,
    apy: 0,
    perWeek: 7500,
  },
  IdeaFundLFBTC: {
    name: 'IdeaFundLFBTC',
    contract: 'IdeaFund',
    depositTokenName: 'LFBTC',
    instructions: 'Exchange LFBTC for CTRL',
    earnTokenName: 'CTRL',
    finished: true,
    poolTVL: "$0",
    sort: 4,
    apy: 0,
    perWeek: 0,
  },
  IdeaFundLIFT: {
    name: 'IdeaFundLIFT',
    contract: 'IdeaFund',
    depositTokenName: 'LIFT',
    instructions: 'Exchange LIFT for CTRL',
    earnTokenName: 'CTRL',
    finished: true,
    poolTVL: "$0",
    sort: 4,
    apy: 0,
    perWeek: 0,
  },
  shortStakealUSDPool: {
    name: 'Earn LIFT by staking alUSD',
    contract: 'shortStakealUSDPool',
    depositTokenName: 'alUSD',
    instructions: 'The scoop on the alUSD pool.  This pool has allocated $50,000 worth of LIFT tokens distributed at .5% per day for 10 days!  To add to this pool you must have alUSD.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: true,
    poolTVL: "$0",
    sort: 4,
    apy: 0,
    perWeek: 0,
  },
  shortStakeiFARMPool: {
    name: 'Earn LIFT by staking iFARM',
    contract: 'shortStakeiFARMPool',
    depositTokenName: 'iFARM',
    instructions: 'The scoop on the iFARM pool.  This pool has allocated $50,000 worth of LIFT tokens distributed at .5% per day for 10 days!  To add to this pool you must have iFARM.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: true,
    poolTVL: "$0",
    sort: 3,
    apy: 0,
    perWeek: 0,
  },
  shortStakeKBTCPool: {
    name: 'Earn LIFT by staking KBTC',
    contract: 'shortStakeKBTCPool',
    depositTokenName: 'KBTC',
    instructions: 'The scoop on the KBTC pool.  This pool has allocated $50,000 worth of LIFT tokens distributed at .5% per day for 10 days!  To add to this pool you must have KBTC.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: true,
    poolTVL: "$0",
    sort: 5,
    apy: 0,
    perWeek: 0,
  },
  shortStakePICKLEPool: {
    name: 'Earn LIFT by staking PICKLE',
    contract: 'shortStakePICKLEPool',
    depositTokenName: 'PICKLE',
    instructions: 'The scoop on the PICKLE pool.  This pool has allocated $50,000 worth of LIFT tokens distributed at .5% per day for 10 days!  To add to this pool you must have PICKLE.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: true,
    poolTVL: "$0",
    sort: 6,
    apy: 0,
    perWeek: 0,
  },
  shortStakeBASv2Pool: {
    name: 'Earn LIFT by staking BASv2',
    contract: 'shortStakeBASv2Pool',
    depositTokenName: 'BASv2',
    instructions: 'The scoop on the BASv2 pool.  This pool has allocated $50,000 worth of LIFT tokens distributed at .5% per day for 10 days!  To add to this pool you must have BASv2.  Now you are earning LIFT tokens congrats!  What you must know about LIFT Tokens is that they are meant to be held!  They will accumulate on this bank page, and then from time to time (you determine your frequency) you will want to move the LIFT Tokens over to the boardroom.  Once you have them in the boardroom the 90 day count down period begins.  Withdrawing your LIFT from the boardroom prior to 90 days has a cost.  If you withdraw on the 1st day of staking you lose 90% of your lift, if you withdraw on the 45th day of staking you lose 45% and on the 89th day of staking you lose 1%?  See the pattern?',
    earnTokenName: 'LIFT',
    finished: true,
    poolTVL: "$0",
    sort: 7,
    apy: 0,
    perWeek: 0,
  },
};

export default configurations[process.env.NODE_ENV || "development"];
